#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

rm -rf [0-9]* constant system layerAveragedData All* log* *.foam processor* postProcessing *.png *.svg dynamicCode 2>/dev/null || true

#------------------------------------------------------------------------------