#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

restore0Dir
touch case.foam
runApplication blockMesh
runApplication $(getApplication)

./Allplot

#------------------------------------------------------------------------------